---
title: "Redes Gaussianas"
format: html
editor: source
---

## 



```{r}
#| echo: False
library(tidyverse)
library(bnlearn)
library(mgcv)

```

```{r}

data = read_csv("data/ckd.csv")
head(data)
```

```{r}
data = data|>
  select(bgr, su, sg, al, sc, bu, pot, sod, bp, rc, hemo, pcv, wc, rc)


clean_data = na.omit(data)
clean_data <- type.convert(clean_data, "numeric")/100*100

head(clean_data)
```

```{r}
best_DAG = hc(clean_data)
```

```{r}
graphviz.plot(best_DAG, shape = "ellipse")
```

```{r}
ckd_fit = bn.fit(best_DAG, data=clean_data)

```
```{r}
#GAM



```




```{r}
##Esto efectivamente coincide con lo de arriba intercept:104.9604284   pot:0.3689704  sod:-0.2220313 
mod_lmrc = lm(rc ~ sc, data = clean_data)
coef(mod_lmrc)
summary(mod_lmrc)

```


```{r}
library(mgcv)
library(gratia)

```

```{r}
##gam(hijo ~ padres)
mod_sc = lm(sc~1, data = clean_data)
mod_bgr = lm(bgr ~ 1, data = clean_data)
mod_al = lm(al ~ 1, data = clean_data)
mod_gam_su = gam(su ~ s(bgr), data = clean_data)
mod_gam_sg = gam(sg ~ s(su, k = 5) + s(al, k =5), data = clean_data, method = "REML")


mod_gam_pot = gam(pot ~ s(sc), data = clean_data, method = "REML")
mod_gam_bu = gam(bu ~ s(sc), data = clean_data, method = "REML")
mod_gam_bp = gam(bp ~ s(sc), data = clean_data, method = "REML")
mod_gam_sod = gam(sod ~ s(sc), data = clean_data, method = "REML")
mod_gam_rc = gam(rc ~ s(sc), data = clean_data, method = "REML")

mod_gam_hemo = gam(hemo ~ s(rc), data = clean_data)
mod_gam_pcv = gam(pcv ~ s(hemo), data = clean_data)
```

```{r}
-1/2*(BIC(mod_sc)+BIC(mod_bgr)+BIC(mod_al)+BIC(mod_gam_su)+BIC(mod_gam_sg)+BIC(mod_gam_pot)+BIC(mod_gam_bu)+BIC(mod_gam_bp)+BIC(mod_gam_sod)+BIC(mod_gam_rc)+BIC(mod_gam_hemo)+BIC(mod_gam_pcv))
-1/2*(AIC(mod_sc)+AIC(mod_bgr)+AIC(mod_al)+AIC(mod_gam_su)+AIC(mod_gam_sg)+AIC(mod_gam_pot)+AIC(mod_gam_bu)+AIC(mod_gam_bp)+AIC(mod_gam_sod)+AIC(mod_gam_rc)+AIC(mod_gam_hemo)+AIC(mod_gam_pcv))
```
```{r}
score(dag, data = clean_data, type = "bic-g")
score(dag, data = clean_data, type = "aic-g")
```



